[build]
  functions = "netlify/functions"
  publish = "dist" # Updated to match the correct build output directory for Vite

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
