[build]
  functions = "netlify/functions"
  publish = "dist" # Updated to match the correct build output directory for Vite

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[dev]
  targetPort = 8081 # Match this to the port Vite is running on
  framework = "vite" # Optional: Explicitly specify the framework
