
[build]
  functions = "netlify/functions"
  publish = "build" # Replace with your build output directory (e.g., "dist" for Vue)

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200